// apps/vue-demo/src/components/TextFormattingDemo.vue
<template>
  <div>
    <h1>Inline formatted text</h1>
    <p>
      You can use many different elements to format your text.
      You can make your text <small>small</small> or you can make it <strong>strong</strong> or <b>bold</b>.
      You can also make it <em>emphasized</em>.
      You can also make it <del>deleted</del> or <s>striked</s>.
      You can also make it <ins>inserted</ins> or <sub>subscripted</sub> or <sup>superscripted</sup>.
      You can also make it <cite>cited</cite> or <q>quoted</q>. 
      You can also make it <dfn>defined</dfn> as well as 
      <i>italic</i>
      <u>underline</u>
      <mark>Highlighting</mark>
      <abbr title="abbreviation">abbr</abbr>
    </p>
    <address>addressed</address>
    <hr />
  </div>
</template>

// apps/react-demo/src/components/TextFormattingDemo.tsx
export function TextFormattingDemo() {
  return (
    <>
      <h1>Inline formatted text</h1>
      <p>
        You can use many different elements to format your text.
        You can make your text <small>small</small> or you can make it <strong>strong</strong> or <b>bold</b>.
        You can also make it <em>emphasized</em>.
        You can also make it <del>deleted</del> or <s>striked</s>.
        You can also make it <ins>inserted</ins> or <sub>subscripted</sub> or <sup>superscripted</sup>.
        You can also make it <cite>cited</cite> or <q>quoted</q>. 
        You can also make it <dfn>defined</dfn> as well as 
        <i>italic</i>
        <u>underline</u>
        <mark>Highlighting</mark>
        <abbr title="abbreviation">abbr</abbr> and lastly <address>addressed</address>
      </p>
      <hr />
    </>
  )
}
