// apps/vue-demo/src/components/TypographyDemo.vue
<template>
  <div>
    <h1>Typography</h1>
    <h1>h1 <small>small h1</small></h1>
    <h2>h2 <small>small h2</small></h2>
    <h3>h3 <small>small h3</small></h3>
    <h4>h4 <small>small h4</small></h4>
    <h5>h5 <small>small h5</small></h5>
    <h6>h6 <small>small h6</small></h6>
    <hr />
  </div>
</template>

// apps/react-demo/src/components/TypographyDemo.tsx
export function TypographyDemo() {
  return (
    <>
      <h1>Typography</h1>
      <h1>h1 <small>small h1</small></h1>
      <h2>h2 <small>small h2</small></h2>
      <h3>h3 <small>small h3</small></h3>
      <h4>h4 <small>small h4</small></h4>
      <h5>h5 <small>small h5</small></h5>
      <h6>h6 <small>small h6</small></h6>
      <hr />
    </>
  )
}
